name: Hello World Redian

on: 
  pull_request:
    types: [opened]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Redian Install pylint
        run: pip install pylint
            pylint taskman
