name: Hello World Redian

on: 
  pull_request:
    types: [opened]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      - name: Redian Install pylint
        run: pip install pylint && pylint taskman
