name: Hello World Redian

on: 
  pull_request:
    types: [opened]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Redian
        run: echo ¨Heello WorldRedian¨
