name: Check with linter on PR

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest  
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
        

      - name: Install pytest-xdist
        run: pip install pytest-xdist

      - name: Upgrade pytest
        run: pip install --upgrade pytest

      - name: Parallel tests
        run: pytest -n auto

      - name: Run pylint
        run: pylint taskman

      - name: Generate Report
        run: |
         pip install codecov
         pip install pytest-cov
         pytest --cov=./ --cov-report=xml
         codecov

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECV_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Scan for security vulnerabilities
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --file=requirements.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/hs-heilbronn-devsecops-gold/my_package:${{ github.sha }}
